import type { Metadata } from "next";
import { DesktopNav } from "./components/desktopNav";
import { MobileNav } from "./components/mobileNav";
import { Footer } from "./components/footer";
import { apfelGrotezk, poppins } from "./styles/fonts";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "DJ Domin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body
        className={`${poppins.variable} ${apfelGrotezk.variable} font-poppins antialiased`}
      >
        <header className="sm:grid justify-end max-w-7xl container m-auto">
          <DesktopNav />
          <MobileNav />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
